---
# Password policy tasks

- name: Configure password policy
  community.general.keycloak_realm:
    auth_keycloak_url: "https://{{ ansible_host }}:{{ keycloak_https_port }}"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    password_policy: "{{ keycloak_password_policy }}"
    state: present
  when: keycloak_password_policy is defined

- name: Configure brute force protection
  community.general.keycloak_realm:
    auth_keycloak_url: "https://{{ ansible_host }}:{{ keycloak_https_port }}"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    brute_force_detection: true
    permanent_lockout: false
    failure_factor: 5
    wait_increment_seconds: 60
    quick_login_check_milli_seconds: 1000
    minimum_quick_login_wait_seconds: 60
    max_failure_wait_seconds: 900
    failure_reset_time_seconds: 43200
  when: keycloak_brute_force_protection | default(true) 