---
- name: Configure SSO for Foreman
  hosts: foreman
  become: true
  vars_files:
    - host_vars/foreman_vars.yml
  roles:
    - role: keycloak_setup
  post_tasks:
    - name: Verify Keycloak installation
      uri:
        url: "http://localhost:{{ keycloak_port }}/health/ready"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    - name: Verify Foreman SSO configuration
      uri:
        url: "https://{{ foreman_host }}/users/auth/keycloak"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10 