---
# Keycloak Configuration
keycloak_version: "21.1.1"
keycloak_admin_user: "admin"
keycloak_admin_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
keycloak_port: 8080
keycloak_https_port: 8443
keycloak_management_port: 9990

# Foreman Integration
foreman_realm_name: "foreman"
foreman_client_id: "foreman"
foreman_client_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

# System Configuration
keycloak_user: "keycloak"
keycloak_group: "keycloak"
keycloak_home: "/opt/keycloak"
keycloak_data_dir: "/var/lib/keycloak"
keycloak_log_dir: "/var/log/keycloak"

# Java Configuration
java_version: "17"
java_home: "/usr/lib/jvm/java-{{ java_version }}-openjdk" 