---
# Keycloak configuration tasks

- name: Check if kc.sh exists
  ansible.builtin.stat:
    path: /opt/keycloak/bin/kc.sh
  register: kc_script

- name: Check if standalone.sh exists (older versions)
  ansible.builtin.stat:
    path: /opt/keycloak/bin/standalone.sh
  register: standalone_script
  when: not kc_script.stat.exists

- name: Configure Keycloak (newer versions)
  ansible.builtin.command:
    cmd: "/opt/keycloak/bin/kc.sh build --db=dev-file"
    chdir: /opt/keycloak
  become: yes
  become_user: keycloak
  register: kc_build
  changed_when: kc_build.rc == 0
  when: kc_script.stat.exists

- name: Enable Keycloak systemd service
  ansible.builtin.systemd:
    name: keycloak
    enabled: yes
    state: started
  register: keycloak_service

- name: Wait for Keycloak to start (HTTP)
  ansible.builtin.uri:
    url: "http://localhost:8080/"
    method: GET
  register: result
  until: result.status is defined and result.status == 200
  retries: 30
  delay: 10
  ignore_errors: yes
  
- name: Check if Keycloak is running
  ansible.builtin.command: 
    cmd: systemctl status keycloak
  register: keycloak_status
  changed_when: false
  failed_when: false
  when: result.status is undefined or result.status != 200

- name: Show Keycloak status
  ansible.builtin.debug:
    var: keycloak_status.stdout_lines
  when: keycloak_status is defined and keycloak_status.stdout_lines is defined

- name: Create Foreman realm
  community.general.keycloak_realm:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    id: "{{ foreman_realm_name }}"
    realm: "{{ foreman_realm_name }}"
    enabled: true
    display_name: "Foreman SSO Realm"
    state: present
  when: result.status is defined and result.status == 200

- name: Create Foreman client
  community.general.keycloak_client:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    client_id: "{{ foreman_client_id }}"
    enabled: true
    redirect_uris:
      - "https://{{ ansible_host }}/users/auth/keycloak/callback"
    web_origins:
      - "+"
    standard_flow_enabled: true
    direct_access_grants_enabled: true
    root_url: "https://{{ ansible_host }}"
    base_url: "/users/auth/keycloak"
    protocol: openid-connect
    state: present
  when: result.status is defined and result.status == 200 