---
# Main tasks for Keycloak setup

- name: Include user management tasks
  ansible.builtin.import_tasks: users.yml

- name: Include group management tasks
  ansible.builtin.import_tasks: groups.yml

- name: Include role management tasks
  ansible.builtin.import_tasks: roles.yml

- name: Include password policy tasks
  ansible.builtin.import_tasks: password_policy.yml

- name: Include verification tasks
  ansible.builtin.import_tasks: verify.yml 