---
# Password policy tasks

- name: Configure password policy
  community.general.keycloak_realm:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    password_policy: "length(12) and forceExpiredPasswordChange(365) and notUsername"
    state: present

- name: Configure brute force protection
  community.general.keycloak_realm:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    brute_force_protected: true
    max_failure_wait_seconds: 900
    minimum_quick_login_wait_seconds: 60
    wait_increment_seconds: 60
    max_failed_login_attempts: 5
    state: present 