---
# User management tasks

- name: Create admin user
  community.general.keycloak_user:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    username: admin
    email: admin@example.com
    first_name: Admin
    last_name: User
    enabled: true
    attributes:
      - key: locale
        value: en
    state: present
  register: admin_user

- name: Set admin user password
  community.general.keycloak_user:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    username: admin
    credentials:
      - type: password
        value: "{{ admin_password }}"
        temporary: false
    state: present

- name: Create regular users
  community.general.keycloak_user:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    username: "{{ item.username }}"
    email: "{{ item.email }}"
    first_name: "{{ item.firstname }}"
    last_name: "{{ item.lastname }}"
    enabled: true
    attributes:
      - key: locale
        value: en
    state: present
  loop: "{{ keycloak_users }}"
  when: keycloak_users is defined

- name: Set user passwords
  community.general.keycloak_user:
    auth_keycloak_url: "http://localhost:8080"
    auth_realm: master
    auth_username: "{{ keycloak_admin_user }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ foreman_realm_name }}"
    username: "{{ item.username }}"
    credentials:
      - type: password
        value: "{{ item.password }}"
        temporary: false
    state: present
  loop: "{{ keycloak_users }}"
  when: keycloak_users is defined 