---
# Verification tasks

- name: Check if Keycloak service is running
  ansible.builtin.command:
    cmd: systemctl is-active keycloak
  register: keycloak_active
  changed_when: false

- name: Show Keycloak service status
  ansible.builtin.debug:
    msg: "Keycloak service status: {{ keycloak_active.stdout }}"

- name: Check Keycloak HTTP endpoint
  ansible.builtin.uri:
    url: "http://localhost:8080/"
    method: GET
  register: http_result
  ignore_errors: yes

- name: Show HTTP endpoint results
  ansible.builtin.debug:
    msg: "HTTP endpoint status: {{ http_result.status | default('unreachable') }}"

- name: Check if firewall might be blocking access
  ansible.builtin.command:
    cmd: firewall-cmd --list-ports
  register: firewall_result
  changed_when: false
  ignore_errors: yes

- name: Show firewall status
  ansible.builtin.debug:
    msg:
      - "Firewall status: {{ firewall_result.stdout_lines | default([]) }}"
      - "If the ports are not listed, you may need to add them: firewall-cmd --permanent --add-port=8443/tcp --add-port=8080/tcp && firewall-cmd --reload"

- name: Wait for Keycloak to be ready
  ansible.builtin.uri:
    url: "http://localhost:8080/realms/master"
    method: GET
    status_code: 200, 404
  register: keycloak_ready
  until: keycloak_ready.status is defined
  retries: 30
  delay: 5
  ignore_errors: yes

- name: Verify Keycloak admin console access
  ansible.builtin.uri:
    url: "http://localhost:8080/admin/"
    method: GET
    status_code: 200, 301, 302
  register: admin_console
  ignore_errors: yes

# Foreman realm verification removed - to be done manually after manual creation 