---
# Verification tasks

- name: Check if Keycloak service is running
  ansible.builtin.systemd:
    name: keycloak
  register: keycloak_service
  changed_when: false

- name: Show Keycloak service status
  ansible.builtin.debug:
    msg: "Keycloak service status: {{ keycloak_service.status.ActiveState }}"

- name: Check Keycloak HTTP endpoint
  ansible.builtin.uri:
    url: "http://localhost:8080/"
    method: GET
    status_code: 200, 301, 302, 307, 308
  register: http_result
  failed_when: false
  changed_when: false

- name: Show HTTP endpoint results
  ansible.builtin.debug:
    msg: "HTTP endpoint status: {{ http_result.status | default('unreachable') }}"

- name: Check if firewall might be blocking access
  ansible.builtin.shell: |
    firewall-cmd --list-all | grep -E '(8080|{{ keycloak_https_port }})'
  register: firewall_check
  failed_when: false
  changed_when: false

- name: Show firewall status
  ansible.builtin.debug:
    msg: 
      - "Firewall status: {{ firewall_check.stdout_lines | default(['No output']) }}"
      - "If the ports are not listed, you may need to add them: firewall-cmd --permanent --add-port={{ keycloak_https_port }}/tcp --add-port=8080/tcp && firewall-cmd --reload"
  when: firewall_check is defined

- name: Wait for Keycloak to be ready
  uri:
    url: "http://localhost:8080/health/ready"
    method: GET
    validate_certs: false
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10

- name: Verify Keycloak admin console access
  uri:
    url: "http://localhost:8080/admin"
    method: GET
    validate_certs: false
    status_code: 200
  register: admin_console

- name: Verify Foreman client configuration
  uri:
    url: "http://localhost:8080/realms/{{ foreman_realm_name }}/.well-known/openid-configuration"
    method: GET
    validate_certs: false
    status_code: 200
  register: openid_config

- name: Verify Foreman SSO endpoint
  uri:
    url: "https://{{ foreman_host }}/users/auth/keycloak"
    method: GET
    validate_certs: false
    status_code: 302
  register: sso_endpoint

- name: Run integration tests
  script: "{{ role_path }}/files/test_integration.sh"
  environment:
    KEYCLOAK_URL: "http://localhost:8080"
    KEYCLOAK_REALM: "{{ foreman_realm_name }}"
    KEYCLOAK_CLIENT: "{{ foreman_client_id }}"
    FOREMAN_URL: "https://{{ foreman_host }}"
    TEST_USER: "{{ keycloak_users[1].username }}"
    TEST_PASSWORD: "{{ keycloak_users[1].password }}"
  register: test_results
  changed_when: false

- name: Display test results
  debug:
    var: test_results.stdout_lines 