name: Deploy SSO

on:
  workflow_dispatch:
    inputs:
      foreman_host:
        description: 'Foreman Server Hostname'
        required: true
      keycloak_version:
        description: 'Keycloak Version'
        required: true
        default: '21.1.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible==8.7.0
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.foreman_host }} >> ~/.ssh/known_hosts
          
      - name: Create inventory
        run: |
          cat > inventory.yml << EOF
          all:
            hosts:
              foreman:
                ansible_host: ${{ github.event.inputs.foreman_host }}
                ansible_user: ${{ secrets.ANSIBLE_USER }}
          EOF
          
      - name: Deploy SSO
        run: |
          cd ansible/playbooks
          ansible-playbook -i ../../inventory.yml site.yml \
            -e "foreman_host=${{ github.event.inputs.foreman_host }}" \
            -e "keycloak_version=${{ github.event.inputs.keycloak_version }}"
            
      - name: Verify Installation
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://${{ github.event.inputs.foreman_host }}/users/auth/keycloak
        continue-on-error: true
        
      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa 